"""addres to classifiers

Revision ID: 031a8b2d6461
Revises: f4109b99ac12
Create Date: 2025-12-18 00:26:53.572488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031a8b2d6461'
down_revision: Union[str, Sequence[str], None] = 'f4109b99ac12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('transport_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['deliverystatuses.id'], ),
    sa.ForeignKeyConstraint(['transport_id'], ['transports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('deliverys')
    op.add_column('customers', sa.Column('country_id', sa.Integer(), nullable=False))
    op.add_column('customers', sa.Column('city_id', sa.Integer(), nullable=False))
    op.add_column('customers', sa.Column('street_id', sa.Integer(), nullable=False))
    op.add_column('customers', sa.Column('house_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'customers', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'customers', 'countries', ['country_id'], ['id'])
    op.create_foreign_key(None, 'customers', 'streets', ['street_id'], ['id'])
    op.create_foreign_key(None, 'customers', 'houses', ['house_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'house_id')
    op.drop_column('customers', 'street_id')
    op.drop_column('customers', 'city_id')
    op.drop_column('customers', 'country_id')
    op.create_table('deliverys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('delivery_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transport_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enterprise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('deliverys_enterprise_id_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('deliverys_order_id_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['deliverystatuses.id'], name=op.f('deliverys_status_id_fkey')),
    sa.ForeignKeyConstraint(['transport_id'], ['transports.id'], name=op.f('deliverys_transport_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deliverys_pkey'))
    )
    op.drop_table('deliveries')
    op.drop_table('streets')
    op.drop_table('houses')
    op.drop_table('countries')
    op.drop_table('cities')
    # ### end Alembic commands ###
