"""empty message

Revision ID: 4fad3c31b64d
Revises: bea58027799c
Create Date: 2025-12-17 12:01:05.404020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fad3c31b64d'
down_revision: Union[str, Sequence[str], None] = 'bea58027799c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'description')
    # ### end Alembic commands ###
