"""empty message

Revision ID: 6d565f0b69dd
Revises: 031a8b2d6461
Create Date: 2025-12-18 00:45:57.657350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d565f0b69dd'
down_revision: Union[str, Sequence[str], None] = '031a8b2d6461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'contact_info',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('customers', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('customers', 'contact_info',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
