"""empty message

Revision ID: 7db3afe002cf
Revises: 2ab575499af8
Create Date: 2025-12-18 17:02:51.282034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db3afe002cf'
down_revision: Union[str, Sequence[str], None] = '2ab575499af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('countries', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('customers', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('deliveries', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('deliverystatuses', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('deposits', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('depositstatuses', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('enterprises', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('enterprisestatuses', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('enterprisetypes', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('houses', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('model3ds', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('orderstatuses', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('positions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('processstatuses', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('processtypes', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('prodmetricses', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('productionprocesses', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('qualifications', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('regions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('streets', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('transports', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('wells', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('wellstatuses', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wellstatuses', 'created_at')
    op.drop_column('wells', 'created_at')
    op.drop_column('users', 'created_at')
    op.drop_column('transports', 'created_at')
    op.drop_column('streets', 'created_at')
    op.drop_column('regions', 'created_at')
    op.drop_column('qualifications', 'created_at')
    op.drop_column('productionprocesses', 'created_at')
    op.drop_column('prodmetricses', 'created_at')
    op.drop_column('processtypes', 'created_at')
    op.drop_column('processstatuses', 'created_at')
    op.drop_column('positions', 'created_at')
    op.drop_column('orderstatuses', 'created_at')
    op.drop_column('orders', 'created_at')
    op.drop_column('model3ds', 'created_at')
    op.drop_column('houses', 'created_at')
    op.drop_column('enterprisetypes', 'created_at')
    op.drop_column('enterprisestatuses', 'created_at')
    op.drop_column('enterprises', 'created_at')
    op.drop_column('depositstatuses', 'created_at')
    op.drop_column('deposits', 'created_at')
    op.drop_column('deliverystatuses', 'created_at')
    op.drop_column('deliveries', 'created_at')
    op.drop_column('customers', 'created_at')
    op.drop_column('countries', 'created_at')
    op.drop_column('cities', 'created_at')
    # ### end Alembic commands ###
