"""empty message

Revision ID: 99d288bc77d5
Revises: 904048cbd312
Create Date: 2025-12-19 11:28:22.713366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d288bc77d5'
down_revision: Union[str, Sequence[str], None] = '904048cbd312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_enterprise_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'enterprise_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('enterprise_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_enterprise_id_fkey'), 'users', 'enterprises', ['enterprise_id'], ['id'])
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
