"""empty message

Revision ID: a7f66fb858c5
Revises: d0fd797e305b
Create Date: 2025-12-18 16:21:09.941706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f66fb858c5'
down_revision: Union[str, Sequence[str], None] = 'd0fd797e305b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model3ds', 'created_at')
    op.drop_column('orders', 'created_at')
    op.drop_column('wells', 'creation_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wells', sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('model3ds', sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
