"""empty message

Revision ID: bea58027799c
Revises: 7e2d9ce498bb
Create Date: 2025-12-16 23:40:49.456463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea58027799c'
down_revision: Union[str, Sequence[str], None] = '7e2d9ce498bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('enterprise_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'enterprises', ['enterprise_id'], ['id'])
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'enterprise_id')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
