"""enterprise address

Revision ID: d0fd797e305b
Revises: 6d565f0b69dd
Create Date: 2025-12-18 01:22:43.118082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0fd797e305b'
down_revision: Union[str, Sequence[str], None] = '6d565f0b69dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprises', sa.Column('country_id', sa.Integer(), nullable=False))
    op.add_column('enterprises', sa.Column('city_id', sa.Integer(), nullable=False))
    op.add_column('enterprises', sa.Column('street_id', sa.Integer(), nullable=False))
    op.add_column('enterprises', sa.Column('house_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'enterprises', 'countries', ['country_id'], ['id'])
    op.create_foreign_key(None, 'enterprises', 'houses', ['house_id'], ['id'])
    op.create_foreign_key(None, 'enterprises', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'enterprises', 'streets', ['street_id'], ['id'])
    op.drop_column('enterprises', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprises', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'enterprises', type_='foreignkey')
    op.drop_constraint(None, 'enterprises', type_='foreignkey')
    op.drop_constraint(None, 'enterprises', type_='foreignkey')
    op.drop_constraint(None, 'enterprises', type_='foreignkey')
    op.drop_column('enterprises', 'house_id')
    op.drop_column('enterprises', 'street_id')
    op.drop_column('enterprises', 'city_id')
    op.drop_column('enterprises', 'country_id')
    # ### end Alembic commands ###
